# version format
version: 0.1.0-pre+{build}
image: Visual Studio 2019

install:
  - appveyor DownloadFile https://github.com/GrognardsFromHell/Dependencies/releases/download/v1.9/dependencies.7z
  - 7z x dependencies.7z
  - nuget install Squirrel.Windows -OutputDirectory Squirrel -Verbosity Detailed

before_build:
  - nuget restore

build_script:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars32.bat"
  - ps: .\UpdateVersion.ps1
  - msbuild TemplePlus.sln /p:Configuration=Release /p:Platform=Win32 /p:MSBuildDefines="_TP_VERSION=%APPVEYOR_BUILD_VERSION%;_TP_COMMIT=%APPVEYOR_REPO_COMMIT%;TP_RELEASE_BUILD" /verbosity:minimal

after_build:
  - ps: .\PackRelease.ps1
  - ps: .\BuildRelease.ps1
  
  # Package the symbol files
  - dependencies\bin\dump_syms.exe Release\TemplePlus.pdb > TemplePlus.sym
  - C:\Python36\python -u deploy_symbols_s3.py TemplePlus.sym
  - 7z a TemplePlusSymbols-%APPVEYOR_BUILD_VERSION%.zip TemplePlus.sym Release\TemplePlus.pdb

  # Release Full with tools and all binaries
  - rd /s /q dist || cd .
  - mkdir dist
  - copy Release\*.exe dist
  - del dist\TemplePlus.exe
  - del dist\*Tests.exe
  - del dist\*.vshost.exe
  - copy Release\*.dll dist
  - copy dependencies\bin\*.dll dist
  - 7z a TemplePlusTools-%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\dist\*

artifacts:
  - path: 'TemplePlus-*.zip'
    name: TemplePlus
  - path: 'TemplePlusSymbols-*.zip'
    name: TemplePlusSymbols
  - path: 'TemplePlusTools-*.zip'
    name: TemplePlusTools
  - path: releases-packages\*

# Deploy to GitHub Releases
# See: https://www.appveyor.com/docs/deployment/github
deploy:
  - provider: GitHub
    description: 'TODO: Release Description'
    draft: true
    prerelease: false
    auth_token:
      secure: Jj836IHtiNEIIYc5FDuGyuBqxQQpii4hv/0KUO2QReGSWq+7VR6XZ5+zaD627upT
    on:
      branch: master
      appveyor_repo_tag: true

test: off
